### ISSUE TITLE
Import keywords existing in the predefined hierarchical keywords

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-georectify-process-airflow#21]
When we import a raster using the REST GeoNode Api, currently GeoNode is adding some custom keywords like the name of the layer, "geotif" ect.
The customer wants to use (from the provided set of keywords in the metadata) just the keywords already defined via the Hierarchical Keywords admin page.

**_Example 1:_**
In GeoNode the following keywords are defined:
A; B; C
If we load an image with the keywords C; D; E (from the XMP metadatadefinition) just the keyword C must be saved.

**_Example 2:_**
In GeoNode the following keywords are defined:
A; B; C
If we load an image with the keywords D; E (from the XMP metadatadefinition). Cause GeoNode needs at least 1 keyword we will use the type of the layer (eg **GeoTif**)

**Comment by mattiagiupponi** [comment]
Keywords now will be handled in two different points:
- Parsing: 
-- the keywords will be extracted from the **XML** and **ONLY** the keywords that are already defined in `GeoNode`, will be preserved and will continue the process
- Storing:
-- Since the `KeywordHandler` in `GeoNode` goes in `append/extend`, the keywords automatically assigned (like filename, GeoTIFF ecc..) are going to be deleted in the [METADATA_STORERS](https://docs.geonode.org/en/master/basic/settings/index.html?#metadata-storers) hook. The hook will loop on all the keywords assigned to the layer and will keep ONLY the keywords that are considered valid from the parsing process.

Example:
Parsing:
| XML | In GeoNode  | Output  | Notes |
|---|---|---|---|
| `k1`,  `k2`,  `k3 `| `k1`,  `k2`,  `k5 ` | `k1` , `k2` | `k3 `is discarded|

Storing:
| XML | Layer  | Output  | Notes |
|---|---|---|---|
| `k1`,  `k2`,  `k3 `| `k1`,  `k2`,  `k6` , `k7` | `k1` , `k2` | `k3 `is discarded. `k6` and `k7` will be deleted |

Ouput:
The Layer uploaded will have `k1` and `k2` as keywords
